In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [ ]:
df = pd.read_csv("/content/bbc-news-data.csv", sep='\t')
df.head()

,category,filename,title,content
0,business,001.txt,Ad sales boost Time Warner profit,Quarterly profits at US media giant TimeWarne...
1,business,002.txt,Dollar gains on Greenspan speech,The dollar has hit its highest level against ...
2,business,003.txt,Yukos unit buyer faces loan claim,The owners of embattled Russian oil giant Yuk...
3,business,004.txt,High fuel prices hit BA's profits,British Airways has blamed high fuel prices f...
4,business,005.txt,Pernod takeover talk lifts Domecq,Shares in UK drinks and food firm Allied Dome...

In [14]:
df["category"].value_counts()

category
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: count, dtype: int64

In [ ]:
documents = df['content']

In [11]:
vectorizer = CountVectorizer(stop_words='english')
word_counts = vectorizer.fit_transform(documents)
feature_names = vectorizer.get_feature_names_out()

lda = LatentDirichletAllocation(n_components=6, random_state=42)
lda.fit(word_counts)

print("Discovered Topics:- ")
for topic_idx, topic in enumerate(lda.components_):
  top_words_idx = topic.argsort()[:-40:-1]
  top_words = [feature_names[i] for i in top_words_idx]
  print(f"Hidden Topic #{topic_idx + 1}: {','.join(top_words)}")

print("\n")

Discovered Topics:-
Hidden Topic #1: said,england,game,win,play,ireland,players,match,cup,year,half,club,second,time,rugby,team,open,france,final,injury,wales,world,good,set,nations,coach,just,united,victory,new,scotland,played,won,try,got,season,beat,player,playing
Hidden Topic #2: said,mr,government,labour,people,election,party,blair,minister,new,told,brown,public,say,plans,prime,tax,bbc,howard,secretary,uk,britain,says,chancellor,home,leader,general,tory,country,law,make,campaign,tories,lord,eu,added,tony,spokesman,think
Hidden Topic #3: said,film,best,music,year,new,awards,mr,uk,award,number,films,people,director,won,actor,star,yukos,british,time,company,years,band,including,million,000,album,games,group,court,movie,tv,actress,sold,legal,industry,make,game,festival
Hidden Topic #4: said,mr,years,told,wales,time,club,like,just,game,way,ebbers,chelsea,ve,home,says,boss,make,real,added,year,trial,fraud,worldcom,bbc,jones,season,don,case,manager,want,come,work,going,mci,old,sullivan,decision,england
Hidden Topic #5: said,year,world,time,games,new,game,just,like,best,years,music,old,bbc,people,won,olympic,make,set,record,good,great,going,race,european,final,champion,british,series,london,long,radio,win,way,britain,think,athens,title,did
Hidden Topic #6: said,year,people,new,market,technology,mobile,mr,company,growth,uk,2004,firm,000,use,world,million,high,companies,economy,sales,users,digital,phone,net,service,firms,services,2005,time,data,according,economic,business,bank,years,months,china,prices

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(documents)

nmf = NMF(n_components=5, random_state=42)
nmf.fit(X)

feature_names = vectorizer.get_feature_names_out()

for idx, topic in enumerate(nmf.components_):
    top_words = [feature_names[i]
                 for i in topic.argsort()[:-20:-1]]
    print(f"Topic {idx+1}: {', '.join(top_words)}")

Topic 1: mobile, people, music, said, digital, phone, technology, users, broadband, software, phones, microsoft, net, video, tv, use, service, online, computer
Topic 2: mr, labour, election, blair, party, brown, said, government, howard, minister, prime, chancellor, tax, tory, tories, leader, campaign, people, britain
Topic 3: england, game, win, wales, said, ireland, team, play, cup, players, match, rugby, france, injury, coach, half, club, world, season
Topic 4: film, best, awards, award, actor, actress, oscar, won, festival, films, director, aviator, comedy, nominated, star, year, nominations, prize, british
Topic 5: growth, economy, said, year, bank, economic, sales, oil, prices, 2004, market, china, rate, dollar, rates, rise, figures, quarter, yukos

- Topic 1: tech
- Topic 2: politics
- Topic 3: sport
- Topic 4: entertainment
- Topic 5: business