In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [40]:
df = pd.read_csv("/content/datamining_pratical1.csv")
df.head()

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,Male,SE,3.70,76.0,0,No,No
1,2,Student_2,24,Male,DS,3.70,76.0,0,No,No
2,3,Student_3,22,Male,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,Male,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,Male,IT,3.14,100.0,5,No,Yes

In [43]:
df["Gender"].value_counts()

Gender
Female    31
Male      15
Fe         2
Ma         2
Name: count, dtype: int64

In [25]:
df.shape

(50, 10)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  50 non-null     int64
 1   Name        50 non-null     object
 2   Age         50 non-null     int64
 3   Gender      50 non-null     object
 4   Department  50 non-null     object
 5   GPA         50 non-null     float64
 6   Attendance  47 non-null     float64
 7   Projects    50 non-null     int64
 8   Internship  50 non-null     object
 9   Graduated   50 non-null     object
dtypes: float64(2), int64(3), object(5)
memory usage: 4.0+ KB

In [27]:
df.describe()

       Student_ID       Age        GPA  Attendance  Projects
count    50.00000  50.00000  50.000000   47.000000   50.0000
mean     25.50000  21.34000   3.001600   74.723404    1.9600
std      14.57738   1.89101   0.548495   16.390217    1.5513
min       1.00000  18.00000   2.000000   50.000000    0.0000
25%      13.25000  20.00000   2.542500   60.000000    0.2500
50%      25.50000  21.00000   3.120000   76.000000    2.0000
75%      37.75000  23.00000   3.397500   87.500000    3.0000
max      50.00000  24.00000   3.940000  100.000000    5.0000

In [28]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
GPA           0
Attendance    3
Projects      0
Internship    0
Graduated     0
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
GPA           0
Attendance    0
Projects      0
Internship    0
Graduated     0
dtype: int64

In [31]:
df = df.drop_duplicates()

In [32]:
df.dtypes

Student_ID      int64
Name           object
Age             int64
Gender         object
Department     object
GPA           float64
Attendance    float64
Projects        int64
Internship     object
Graduated      object
dtype: object

In [16]:
df["Gender"] = df["Gender"].astype(int)

ValueError: invalid literal for int() with base 10: 'Male'

In [21]:
df["Gender"] = df["Gender"].apply(lambda x: 1 if x == "Male" else 0)
df["Gender"].head()

0    0
1    0
2    0
3    0
4    0
Name: Gender, dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder
encorder = LabelEncoder()
df["Gender"] = encorder.fit_transform(df["Gender"])
df["Gender"].head()

0    0
1    0
2    0
3    0
4    0
Name: Gender, dtype: int64

In [44]:
dic = {
    "Male" : 1,
    "Ma": 1,
    "Fe":0,
    "Female" : 0
}
df["Gender"] = df["Gender"].map(dic)

In [45]:
df["Gender"].value_counts()

Gender
0    33
1    17
Name: count, dtype: int64

In [46]:
df

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Projects,Internship,Graduated
0,1,Student_1,24,1,SE,3.70,76.0,0,No,No
1,2,Student_2,24,1,DS,3.70,76.0,0,No,No
2,3,Student_3,22,1,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,1,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,1,IT,3.14,100.0,5,No,Yes
5,6,Student_6,22,1,SE,3.34,91.0,4,No,Yes
6,7,Student_7,22,0,DS,3.33,93.0,2,No,No
7,8,Student_8,24,0,CS,3.18,73.0,3,No,No
8,9,Student_9,19,1,IT,2.55,64.0,3,No,Yes
9,10,Student_10,20,0,DS,3.12,81.0,2,No,Yes
10,11,Student_11,24,0,CS,2.77,81.0,3,Yes,No
11,12,Student_12,20,0,DS,3.94,73.0,2,No,Yes
12,13,Student_13,20,0,CS,3.70,90.0,1,No,No
13,14,Student_14,22,1,IT,3.44,98.0,2,Yes,Yes
14,15,Student_15,21,0,SE,3.12,98.0,2,Yes,No
15,16,Student_16,20,1,CS,2.51,61.0,3,Yes,Yes
16,17,Student_17,23,0,DS,2.08,88.0,3,Yes,No
17,18,Student_18,22,0,IT,3.42,51.0,0,No,Yes
18,19,Student_19,19,0,CS,2.22,52.0,0,No,Yes
19,20,Student_20,21,1,DS,2.88,98.0,1,No,No
20,21,Student_21,23,0,DS,2.40,86.0,0,No,Yes
21,22,Student_22,23,1,DS,3.79,98.0,2,No,No
22,23,Student_23,19,0,CS,2.95,66.0,3,No,Yes
23,24,Student_24,21,1,CS,3.13,98.0,0,Yes,No
24,25,Student_25,22,0,CS,3.39,51.0,0,No,Yes
25,26,Student_26,18,1,SE,2.28,51.0,1,Yes,No
26,27,Student_27,21,1,CS,3.21,77.0,5,Yes,Yes
27,28,Student_28,19,0,CS,3.67,72.0,1,No,No
28,29,Student_29,23,1,CS,2.41,86.0,2,Yes,Yes
29,30,Student_30,22,0,SE,3.89,81.0,3,No,No
30,31,Student_31,21,0,CS,3.20,58.0,1,Yes,No
31,32,Student_32,18,0,DS,3.39,50.0,0,No,No
32,33,Student_33,18,0,CS,3.76,68.0,3,Yes,Yes
33,34,Student_34,20,0,DS,3.25,51.0,3,No,No
34,35,Student_35,20,0,DS,2.59,93.0,0,No,Yes
35,36,Student_36,24,0,DS,2.21,NaN,1,No,No
36,37,Student_37,19,0,SE,2.91,81.0,0,No,Yes
37,38,Student_38,21,0,SE,2.44,55.0,5,No,No
38,39,Student_39,21,0,SE,2.83,81.0,3,Yes,Yes
39,40,Student_40,24,0,CS,3.77,NaN,4,Yes,Yes
40,41,Student_41,23,1,DS,2.65,60.0,4,Yes,No
41,42,Student_42,23,1,SE,2.24,66.0,2,No,Yes
42,43,Student_43,24,0,SE,3.40,87.0,0,Yes,Yes
43,44,Student_44,23,0,CS,3.60,NaN,0,No,No
44,45,Student_45,20,0,SE,2.54,54.0,2,No,Yes
45,46,Student_46,21,0,CS,3.30,83.0,2,Yes,Yes
46,47,Student_47,24,0,IT,2.00,55.0,2,Yes,Yes
47,48,Student_48,21,0,SE,2.71,71.0,3,No,No
48,49,Student_49,18,0,IT,2.61,60.0,5,Yes,Yes
49,50,Student_50,20,0,CS,2.33,97.0,0,No,No

In [50]:
df = df.rename(columns={"Projects": "Project"})

In [51]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'GPA',
       'Attendance', 'Project', 'Internship', 'Graduated'],
      dtype='object')

In [52]:
df.head()

,Student_ID,Name,Age,Gender,Department,GPA,Attendance,Project,Internship,Graduated
0,1,Student_1,24,1,SE,3.70,76.0,0,No,No
1,2,Student_2,24,1,DS,3.70,76.0,0,No,No
2,3,Student_3,22,1,SE,2.90,50.0,3,Yes,No
3,4,Student_4,24,1,DS,2.19,82.0,2,Yes,No
4,5,Student_5,20,1,IT,3.14,100.0,5,No,Yes

In [54]:
invalid_attendance = df[(df["Attendance"] > 100) | (df["Attendance"] < 0)]
invalid_attendance.value_counts()

Series([], Name: count, dtype: int64)

In [61]:
df.loc[50] = {'Student_ID': len(df), 'Name': f"Student_{len(df)}", 'Age': df.Age.median(),"Gender":1,"Department":"SE","GPA":3.6,"Attendance":9000,"Project":4,"Internship":"Yes","Graduated":"No"}

In [62]:
df.iloc[len(df) - 1]

Student_ID            51
Name          Student_51
Age                 21.0
Gender                 1
Department            SE
GPA                  3.6
Attendance        9000.0
Project                4
Internship           Yes
Graduated             No
Name: 50, dtype: object

In [63]:
df["Attendance"].mean()

np.float64(260.6666666666667)

In [65]:
invalid_attendance = df[(df["Attendance"] > 100) | (df["Attendance"] < 0)]
invalid_attendance.value_counts()

Student_ID  Name        Age   Gender  Department  GPA  Attendance  Project  Internship  Graduated
51          Student_51  21.0  1       SE          3.6  9000.0      4        Yes         No           1
Name: count, dtype: int64

In [66]:
df.to_csv("Cleaned_School_attendance.csv",index=False)

In [67]:
from google.colab import files
files.download("Cleaned_School_attendance.csv")